"""add student_code to students

Revision ID: 5e31f594dece
Revises: 0014_refactor_schema
Create Date: 2026-03-20 17:18:22.898281+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e31f594dece'
down_revision: Union[str, None] = '0014_refactor_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_dedup', table_name='attendance_records')
    op.drop_index('ix_attendance_records_class_id', table_name='attendance_records')
    op.drop_index('ix_attendance_records_id', table_name='attendance_records')
    op.drop_index('ix_attendance_records_student_id', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.alter_column('attendance', 'sync_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendance', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_attendance_session', table_name='attendance')
    op.drop_index('idx_attendance_student', table_name='attendance')
    op.drop_index('ix_attendance_created_at', table_name='attendance')
    op.create_index(op.f('ix_attendance_deleted_at'), 'attendance', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_attendance_device_id'), 'attendance', ['device_id'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_session_id'), 'attendance', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.drop_table_comment(
        'attendance',
        existing_comment='New attendance table - replaces logic from attendance_records',
        schema=None
    )
    op.add_column('course_enrollments', sa.Column('course_id', sa.UUID(), nullable=False))
    op.alter_column('course_enrollments', 'enrolled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_classroom_students_classroom', table_name='course_enrollments')
    op.drop_index('idx_classroom_students_student', table_name='course_enrollments')
    op.drop_constraint('uq_classroom_student', 'course_enrollments', type_='unique')
    op.create_index(op.f('ix_course_enrollments_course_id'), 'course_enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_student_id'), 'course_enrollments', ['student_id'], unique=False)
    op.create_index('ix_enrollment_course_student', 'course_enrollments', ['course_id', 'student_id'], unique=False)
    op.create_unique_constraint('uq_enrollment_course_student', 'course_enrollments', ['course_id', 'student_id'])
    op.drop_constraint('classroom_students_classroom_id_fkey', 'course_enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'course_enrollments', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_column('course_enrollments', 'classroom_id')
    op.add_column('courses', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('courses', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('courses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_classes_id', table_name='courses')
    op.drop_index('ix_classes_teacher_id', table_name='courses')
    op.create_index(op.f('ix_courses_deleted_at'), 'courses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_instructor_id'), 'courses', ['instructor_id'], unique=False)
    op.add_column('devices', sa.Column('device_code', sa.String(length=50), nullable=False))
    op.add_column('devices', sa.Column('room', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('devices', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('devices', 'device_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('devices', 'device_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('devices', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('devices_api_key_key', 'devices', type_='unique')
    op.drop_index('idx_devices_classroom', table_name='devices')
    op.create_index(op.f('ix_devices_course_id'), 'devices', ['course_id'], unique=False)
    op.create_index(op.f('ix_devices_deleted_at'), 'devices', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_devices_device_code'), 'devices', ['device_code'], unique=True)
    op.drop_column('devices', 'location')
    op.drop_column('devices', 'device_secret')
    op.drop_column('devices', 'last_token_at')
    op.drop_column('devices', 'api_key')
    op.drop_column('devices', 'last_seen')
    op.add_column('face_embeddings', sa.Column('embedding', sa.JSON(), nullable=False))
    op.add_column('face_embeddings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('face_embeddings', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_face_embeddings_device', table_name='face_embeddings')
    op.drop_index('ix_face_embeddings_active_student', table_name='face_embeddings', postgresql_where='(is_active = true)')
    op.create_index(op.f('ix_face_embeddings_deleted_at'), 'face_embeddings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_face_embeddings_device_id'), 'face_embeddings', ['device_id'], unique=False)
    op.create_index(op.f('ix_face_embeddings_is_active'), 'face_embeddings', ['is_active'], unique=False)
    op.create_index('ix_face_embeddings_student', 'face_embeddings', ['student_id'], unique=False)
    op.drop_column('face_embeddings', 'embedding_data')
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_refresh_tokens_token_jti', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_jti'), 'refresh_tokens', ['token_jti'], unique=True)
    op.add_column('schedules', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('schedules', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('schedules', 'room',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_schedules_classroom', table_name='schedules')
    op.drop_index('idx_schedules_day', table_name='schedules')
    op.drop_constraint('uq_schedule', 'schedules', type_='unique')
    op.create_index(op.f('ix_schedules_course_id'), 'schedules', ['course_id'], unique=False)
    op.create_index(op.f('ix_schedules_deleted_at'), 'schedules', ['deleted_at'], unique=False)
    op.create_unique_constraint('uq_schedule_course_day_slot', 'schedules', ['course_id', 'day_of_week', 'time_slot_id'])
    op.drop_table_comment(
        'schedules',
        existing_comment='Weekly class schedule - links classroom to day and time slot',
        schema=None
    )
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_sessions_status', table_name='sessions')
    op.create_index(op.f('ix_sessions_course_id'), 'sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_sessions_deleted_at'), 'sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.drop_table_comment(
        'sessions',
        existing_comment='Attendance session - actual instance of a scheduled class',
        schema=None
    )
    op.add_column('student_groups', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('student_groups', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('student_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('student_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('academic_classes_code_key', 'student_groups', type_='unique')
    op.drop_index('idx_academic_classes_code', table_name='student_groups')
    op.create_index(op.f('ix_student_groups_advisor_id'), 'student_groups', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_student_groups_code'), 'student_groups', ['code'], unique=True)
    op.create_index(op.f('ix_student_groups_deleted_at'), 'student_groups', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_student_groups_id'), 'student_groups', ['id'], unique=False)
    op.add_column('students', sa.Column('student_code', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('students', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.drop_index('idx_students_academic_class', table_name='students')
    op.drop_constraint('uq_students_user_id', 'students', type_='unique')
    op.drop_index('ix_students_user_id', table_name='students')
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_index(op.f('ix_students_deleted_at'), 'students', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_students_student_group_id'), 'students', ['student_group_id'], unique=False)
    op.create_unique_constraint(None, 'students', ['student_code'])
    op.drop_constraint('students_user_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('students', 'job_title')
    op.add_column('teachers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('teachers_user_id_key', 'teachers', type_='unique')
    op.drop_index('ix_teachers_user_id', table_name='teachers')
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=True)
    op.create_index(op.f('ix_teachers_deleted_at'), 'teachers', ['deleted_at'], unique=False)
    op.alter_column('time_slots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'time_slots', ['period_number'])
    op.drop_table_comment(
        'time_slots',
        existing_comment='Global period definitions for school timetable',
        schema=None
    )
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'student'::character varying"),
               existing_nullable=False)
    op.create_table_comment(
        'time_slots',
        'Global period definitions for school timetable',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'time_slots', type_='unique')
    op.alter_column('time_slots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_teachers_deleted_at'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.create_index('ix_teachers_user_id', 'teachers', ['user_id'], unique=False)
    op.create_unique_constraint('teachers_user_id_key', 'teachers', ['user_id'])
    op.drop_column('teachers', 'deleted_at')
    op.add_column('students', sa.Column('job_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_user_id_fkey', 'students', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_index(op.f('ix_students_student_group_id'), table_name='students')
    op.drop_index(op.f('ix_students_deleted_at'), table_name='students')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.create_index('ix_students_user_id', 'students', ['user_id'], unique=False)
    op.create_unique_constraint('uq_students_user_id', 'students', ['user_id'])
    op.create_index('idx_students_academic_class', 'students', ['student_group_id'], unique=False)
    op.drop_column('students', 'updated_by')
    op.drop_column('students', 'created_by')
    op.drop_column('students', 'student_code')
    op.drop_index(op.f('ix_student_groups_id'), table_name='student_groups')
    op.drop_index(op.f('ix_student_groups_deleted_at'), table_name='student_groups')
    op.drop_index(op.f('ix_student_groups_code'), table_name='student_groups')
    op.drop_index(op.f('ix_student_groups_advisor_id'), table_name='student_groups')
    op.create_index('idx_academic_classes_code', 'student_groups', ['code'], unique=False)
    op.create_unique_constraint('academic_classes_code_key', 'student_groups', ['code'])
    op.alter_column('student_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('student_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('student_groups', 'updated_by')
    op.drop_column('student_groups', 'created_by')
    op.create_table_comment(
        'sessions',
        'Attendance session - actual instance of a scheduled class',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_deleted_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_course_id'), table_name='sessions')
    op.create_index('idx_sessions_status', 'sessions', ['status'], unique=False)
    op.alter_column('sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'scheduled'::character varying"),
               nullable=True)
    op.create_table_comment(
        'schedules',
        'Weekly class schedule - links classroom to day and time slot',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('uq_schedule_course_day_slot', 'schedules', type_='unique')
    op.drop_index(op.f('ix_schedules_deleted_at'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_course_id'), table_name='schedules')
    op.create_unique_constraint('uq_schedule', 'schedules', ['course_id', 'day_of_week', 'time_slot_id'])
    op.create_index('idx_schedules_day', 'schedules', ['day_of_week'], unique=False)
    op.create_index('idx_schedules_classroom', 'schedules', ['course_id'], unique=False)
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'room',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('schedules', 'updated_by')
    op.drop_column('schedules', 'created_by')
    op.drop_index(op.f('ix_refresh_tokens_token_jti'), table_name='refresh_tokens')
    op.create_index('ix_refresh_tokens_token_jti', 'refresh_tokens', ['token_jti'], unique=False)
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.add_column('face_embeddings', sa.Column('embedding_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index('ix_face_embeddings_student', table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_is_active'), table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_device_id'), table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_deleted_at'), table_name='face_embeddings')
    op.create_index('ix_face_embeddings_active_student', 'face_embeddings', ['student_id'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_face_embeddings_device', 'face_embeddings', ['device_id'], unique=False)
    op.alter_column('face_embeddings', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('face_embeddings', 'deleted_at')
    op.drop_column('face_embeddings', 'embedding')
    op.add_column('devices', sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('api_key', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('last_token_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('device_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_devices_device_code'), table_name='devices')
    op.drop_index(op.f('ix_devices_deleted_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_course_id'), table_name='devices')
    op.create_index('idx_devices_classroom', 'devices', ['course_id'], unique=False)
    op.create_unique_constraint('devices_api_key_key', 'devices', ['api_key'])
    op.alter_column('devices', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('devices', 'device_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('devices', 'device_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('devices', 'updated_by')
    op.drop_column('devices', 'created_by')
    op.drop_column('devices', 'room')
    op.drop_column('devices', 'device_code')
    op.drop_index(op.f('ix_courses_instructor_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_deleted_at'), table_name='courses')
    op.create_index('ix_classes_teacher_id', 'courses', ['instructor_id'], unique=False)
    op.create_index('ix_classes_id', 'courses', ['id'], unique=False)
    op.alter_column('courses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('courses', 'updated_by')
    op.drop_column('courses', 'created_by')
    op.add_column('course_enrollments', sa.Column('classroom_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'course_enrollments', type_='foreignkey')
    op.create_foreign_key('classroom_students_classroom_id_fkey', 'course_enrollments', 'courses', ['classroom_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_enrollment_course_student', 'course_enrollments', type_='unique')
    op.drop_index('ix_enrollment_course_student', table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_student_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_course_id'), table_name='course_enrollments')
    op.create_unique_constraint('uq_classroom_student', 'course_enrollments', ['classroom_id', 'student_id'])
    op.create_index('idx_classroom_students_student', 'course_enrollments', ['student_id'], unique=False)
    op.create_index('idx_classroom_students_classroom', 'course_enrollments', ['classroom_id'], unique=False)
    op.alter_column('course_enrollments', 'enrolled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('course_enrollments', 'course_id')
    op.create_table_comment(
        'attendance',
        'New attendance table - replaces logic from attendance_records',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_session_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_device_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_deleted_at'), table_name='attendance')
    op.create_index('ix_attendance_created_at', 'attendance', ['created_at'], unique=False)
    op.create_index('idx_attendance_student', 'attendance', ['student_id'], unique=False)
    op.create_index('idx_attendance_session', 'attendance', ['session_id'], unique=False)
    op.alter_column('attendance', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendance', 'sync_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('record_type', sa.VARCHAR(length=10), server_default=sa.text("'checkin'::character varying"), autoincrement=False, nullable=False),
    sa.Column('checkin_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sync_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'present'::character varying"), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['courses.id'], name='attendance_records_class_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='attendance_records_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='attendance_records_pkey'),
    comment='LEGACY TABLE - Data has been migrated to attendance table. Use attendance instead for new records.'
    )
    op.create_index('ix_attendance_records_student_id', 'attendance_records', ['student_id'], unique=False)
    op.create_index('ix_attendance_records_id', 'attendance_records', ['id'], unique=False)
    op.create_index('ix_attendance_records_class_id', 'attendance_records', ['class_id'], unique=False)
    op.create_index('ix_attendance_dedup', 'attendance_records', ['student_id', 'checkin_time', 'record_type'], unique=False)
    # ### end Alembic commands ###
