"""refactor student_groups drop faculty course_year add department_id

Revision ID: c3385166bfd9
Revises: 0026_drop_schedule_device_room_columns
Create Date: 2026-03-23 03:20:17.236591+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3385166bfd9'
down_revision: Union[str, None] = '0026_drop_schedule_device_room_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_enrollment_active', table_name='course_enrollments')
    op.alter_column('courses', 'attendance_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('courses', 'attendance_before_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('courses', 'attendance_after_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_courses_department_id'), 'courses', ['department_id'], unique=False)
    op.alter_column('departments', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('departments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('departments_code_key', 'departments', type_='unique')
    op.drop_index('uq_departments_code', table_name='departments', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.drop_column('departments', 'description')
    op.drop_index('ix_devices_active_room', table_name='devices', postgresql_where='(is_active = true)')
    op.drop_index('ix_face_embeddings_active', table_name='face_embeddings', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.drop_index('ix_sessions_schedule_date', table_name='sessions')
    op.drop_index('uq_sessions_schedule_date', table_name='sessions', postgresql_where='(deleted_at IS NULL)')
    op.add_column('student_groups', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_student_groups_department_id'), 'student_groups', ['department_id'], unique=False)
    op.create_foreign_key(None, 'student_groups', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_column('student_groups', 'faculty')
    op.drop_column('student_groups', 'course_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_groups', sa.Column('course_year', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('student_groups', sa.Column('faculty', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student_groups', type_='foreignkey')
    op.drop_index(op.f('ix_student_groups_department_id'), table_name='student_groups')
    op.drop_column('student_groups', 'department_id')
    op.create_index('uq_sessions_schedule_date', 'sessions', ['schedule_id', 'session_date'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_sessions_schedule_date', 'sessions', ['schedule_id', 'session_date'], unique=False)
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.create_index('ix_face_embeddings_active', 'face_embeddings', ['student_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_devices_active_room', 'devices', ['device_code', 'deleted_at'], unique=False, postgresql_where='(is_active = true)')
    op.add_column('departments', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.create_index('uq_departments_code', 'departments', ['code'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_unique_constraint('departments_code_key', 'departments', ['code'])
    op.alter_column('departments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('departments', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_courses_department_id'), table_name='courses')
    op.alter_column('courses', 'attendance_after_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=False)
    op.alter_column('courses', 'attendance_before_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=False)
    op.alter_column('courses', 'attendance_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'fixed'::character varying"),
               existing_nullable=False)
    op.create_index('ix_course_enrollment_active', 'course_enrollments', ['course_id', 'student_id'], unique=False)
    # ### end Alembic commands ###
