"""add_total_sessions_credits_to_courses

Revision ID: 3da1ca04d919
Revises: add_enrollment_counts
Create Date: 2026-03-28 19:54:06.036552+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da1ca04d919'
down_revision: Union[str, None] = 'add_enrollment_counts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_minutes_diff', table_name='attendance')
    op.drop_index('ix_attendance_audit_id', table_name='attendance_audit_logs')
    op.create_index(op.f('ix_attendance_audit_logs_id'), 'attendance_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_audit_logs_session_id'), 'attendance_audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_audit_logs_student_id'), 'attendance_audit_logs', ['student_id'], unique=False)
    op.alter_column('device_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('devices', 'is_global',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('devices', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'ACTIVE'::character varying"),
               existing_nullable=False)
    op.alter_column('devices', 'is_global',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('device_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_attendance_audit_logs_student_id'), table_name='attendance_audit_logs')
    op.drop_index(op.f('ix_attendance_audit_logs_session_id'), table_name='attendance_audit_logs')
    op.drop_index(op.f('ix_attendance_audit_logs_id'), table_name='attendance_audit_logs')
    op.create_index('ix_attendance_audit_id', 'attendance_audit_logs', ['id'], unique=False)
    op.create_index('ix_attendance_minutes_diff', 'attendance', ['minutes_diff'], unique=False)
    # ### end Alembic commands ###
